### ISSUE TITLE
Support for additional gametypes on GG

### ISSUE THREAD

**Issue by ItalyToast** [ItalyToast/PokerHandHistoryParser#94]
Some common games that are currently missing:
- FixedLimitHoldem
- PotLimitHoldem
- NoLimitOmaha
- PotLimitOmaha
- FixedLimitOmaha
- And More

@RuijieZ you dont happen to have some hh laying around? Play money works just fine

**Comment by RuijieZ** [comment]
I also have access to 3 seated Sit & Go if you want any of that.

**Comment by ItalyToast** [comment]
> I only have access to PLO and PLO-5, both are pot-limited. Let me know if you need more hands.

will do

> I also have access to 3 seated Sit & Go if you want any of that.

I'm fine for now 😊
